version: '2.0'
services:
  taco:
    image: taco:0.0.1-20161121-15439
    links:
      - 'taco_server:api'
    ports:
      - '8080:80'
  taco_server:
    image: taco_server:0.0.1-20161121-160047
    ports:
      - '9000:80'
